/* Builds src/data/news.json from public NFL news RSS feeds.
   Runs on a schedule in CI. Run locally: npm run news */

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { XMLParser } from 'fast-xml-parser';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../src/data/news.json');

const FEEDS = [
  { source: 'ESPN', url: 'https://www.espn.com/espn/rss/nfl/news' },
  { source: 'PFT', url: 'https://profootballtalk.nbcsports.com/feed/' },
  { source: 'CBS Sports', url: 'https://www.cbssports.com/rss/headlines/nfl/' },
];

const MAX_ITEMS = 36;
const MAX_AGE_DAYS = 20;

// safety net: RSS feeds occasionally bleed in other sports — drop the obvious ones
const OFF_TOPIC = /\b(MLB|NBA|NHL|WNBA|Orioles|Yankees|Mets|Dodgers|Phillies|Angels|Athletics|Lakers|Celtics|Premier League|La ?Liga|UEFA|soccer|tennis|golf|NASCAR|UFC|boxing|cricket|college (football|basketball)|CFB|NCAA|men's basketball|women's basketball)\b/i;

const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' });

function clean(html = '') {
  return String(html)
    .replace(/<!\[CDATA\[|\]\]>/g, '')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

async function pullFeed({ source, url }) {
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; ArmchairQuarterbacksBot/1.0)' },
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const xml = await res.text();
    const doc = parser.parse(xml);
    const items = doc?.rss?.channel?.item || doc?.feed?.entry || [];
    return (Array.isArray(items) ? items : [items]).map((it) => {
      const link = typeof it.link === 'object' ? it.link['@_href'] || it.link['#text'] : it.link;
      const dateRaw = it.pubDate || it.published || it.updated || it['dc:date'];
      return {
        source,
        title: clean(it.title?.['#text'] || it.title),
        url: (link || '').trim(),
        summary: clean(it.description?.['#text'] || it.description || it.summary || '').slice(0, 220),
        publishedAt: dateRaw ? new Date(dateRaw).toISOString() : null,
      };
    });
  } catch (err) {
    console.warn(`  ! ${source}: ${err.message}`);
    return [];
  }
}

async function main() {
  const results = await Promise.all(FEEDS.map(pullFeed));
  const cutoff = Date.now() - MAX_AGE_DAYS * 86400000;
  const seen = new Set();
  const items = results
    .flat()
    .filter((n) => n.title && n.url)
    .filter((n) => !OFF_TOPIC.test(`${n.title} ${n.summary}`))
    .filter((n) => !n.publishedAt || new Date(n.publishedAt).getTime() > cutoff)
    .filter((n) => {
      const key = n.title.toLowerCase().slice(0, 60);
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => (b.publishedAt || '').localeCompare(a.publishedAt || ''))
    .slice(0, MAX_ITEMS);

  const out = {
    _comment: 'Auto-generated by scripts/fetch-news.mjs from public NFL RSS feeds.',
    generatedAt: new Date().toISOString(),
    sources: [...new Set(items.map((i) => i.source))],
    items,
  };
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');
  console.log(`✓ news.json — ${items.length} items from ${out.sources.join(', ') || 'no feeds'}`);
}

main().catch((e) => {
  console.error('fetch-news failed:', e.message);
  process.exitCode = 1;
});
